//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKino.Desktop.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalan broj karata je 10..
        /// </summary>
        internal static string Int_BrojKarata {
            get {
                return ResourceManager.GetString("Int_BrojKarata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijenu projekcije unosite brojem..
        /// </summary>
        internal static string Int_CijenaProjekcije {
            get {
                return ResourceManager.GetString("Int_CijenaProjekcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti ispravan email..
        /// </summary>
        internal static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti ime..
        /// </summary>
        internal static string Text_Ime {
            get {
                return ResourceManager.GetString("Text_Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni text mora imati najmanje 3, a najviše 200 karaktera..
        /// </summary>
        internal static string Text_Length_3_200 {
            get {
                return ResourceManager.GetString("Text_Length_3_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti link..
        /// </summary>
        internal static string Text_Link {
            get {
                return ResourceManager.GetString("Text_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv..
        /// </summary>
        internal static string Text_Naziv {
            get {
                return ResourceManager.GetString("Text_Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti opis..
        /// </summary>
        internal static string Text_Opis {
            get {
                return ResourceManager.GetString("Text_Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti opis. (min 15 karaktera).
        /// </summary>
        internal static string Text_Opis_15_K {
            get {
                return ResourceManager.GetString("Text_Opis_15_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti prezime..
        /// </summary>
        internal static string Text_Prezime {
            get {
                return ResourceManager.GetString("Text_Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je unijeti naziv produkcijske kuće..
        /// </summary>
        internal static string Text_PrKuca {
            get {
                return ResourceManager.GetString("Text_PrKuca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra mora sadrzavati 6-15 karaktera..
        /// </summary>
        internal static string Text_Sifra {
            get {
                return ResourceManager.GetString("Text_Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifre se ne poklapaju..
        /// </summary>
        internal static string Text_Sifra_Potvrda {
            get {
                return ResourceManager.GetString("Text_Sifra_Potvrda", resourceCulture);
            }
        }
    }
}
